_target_: instant_avatar.datasets.peoplesnapshot.PeopleSnapshotDataModule
name: peoplesnapshot
subject: female-4-casual
gender: female
opt:
  dataroot: ./data/PeopleSnapshot/${dataset.subject}/
  subject: ${dataset.subject}
  train:
    num_workers: 8
    batch_size: 4
    start: 0
    end: 335
    skip: 4
    downscale: 2
    sampler: ${sampler}
    fitting: ${model.opt.optimize_SMPL.enable}
    refine: ${model.opt.optimize_SMPL.is_refine}
  val:
    num_workers: 0
    batch_size: 1
    start: 335
    end: 335
    skip: 4
    downscale: 2
  test:
    num_workers: 4
    batch_size: 1
    start: 335
    end: 523
    skip: 4
    downscale: 2